version: '3'

services:
  php:
    build: .
    command: "tail -f /dev/null"
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
  redis:
    image: redis
    command: redis-server --requirepass password123
    environment: { TERM: xterm }
    restart: unless-stopped
